name: Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # roda todo dia à meia-noite
  workflow_dispatch:       # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Pac-Man Graph
        uses: Platane/snk@master
        with:
          github_user_name: allysonaggp   # <-- coloque seu usuário aqui
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Push to output branch
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate Pac-Man graph"
          add: "output/*.svg"
